const SOCKET_RECEIVED_MESSAGE = "SOCKET_RECEIVED_MESSAGE";
const SOCKET_ADD_CONTACT = "SOCKET_ADD_CONTACT";
const SOCKET_DELETE_MESSAGE = "SOCKET_DELETE_MESSAGE";

module.exports = {
    SOCKET_RECEIVED_MESSAGE,
    SOCKET_ADD_CONTACT,
    SOCKET_DELETE_MESSAGE
}